name: Octo Organization CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile latex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "src/*/conspect.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
          work_in_root_file_dir: true
         extra_fonts: |
           ./otf-cm-unicode/*.otf
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.pdf
